export const PACK_CARDS = [
  {
    id: 6,
    name: 'Charizard',
    type: 'Fire',
    rarity: 'legendary',
    power: 330,
    description: 'Spits fire hot enough to melt boulders. Known to cause forest fires unintentionally.',
    primaryColor: '#b83210',
    secondaryColor: '#e85828',
    accentColor: '#ffd040',
    borderColor: '#ffd040',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
  },
  {
    id: 150,
    name: 'Mewtwo',
    type: 'Psychic',
    rarity: 'rare',
    power: 250,
    description: "A Pokémon created by recombining Mew's genes. Said to be the most powerful Pokémon ever.",
    primaryColor: '#6830a0',
    secondaryColor: '#9858c8',
    accentColor: '#e090ff',
    borderColor: '#c078e8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
  },
  {
    id: 130,
    name: 'Gyarados',
    type: 'Water',
    rarity: 'rare',
    power: 220,
    description: 'Once it begins to rampage, a Gyarados will burn everything down, even in a harsh storm.',
    primaryColor: '#0c4870',
    secondaryColor: '#1870a8',
    accentColor: '#60c8f0',
    borderColor: '#3898c8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
  },
  {
    id: 94,
    name: 'Gengar',
    type: 'Ghost',
    rarity: 'uncommon',
    power: 140,
    description: 'Said to lurk in the shadows of rooms, giggling while watching frightened people.',
    primaryColor: '#3a1860',
    secondaryColor: '#6030a0',
    accentColor: '#c090f0',
    borderColor: '#8050b8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
  },
  {
    id: 25,
    name: 'Pikachu',
    type: 'Electric',
    rarity: 'common',
    power: 70,
    description: 'The electric sacs in its cheeks allow it to unleash powerful thunderbolts without warning.',
    primaryColor: '#a07810',
    secondaryColor: '#d0a820',
    accentColor: '#ffe840',
    borderColor: '#c09018',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
  },
  {
    id: 9,
    name: 'Blastoise',
    type: 'Water',
    rarity: 'rare',
    power: 210,
    description: 'It crushes its foe under its heavy body to cause fainting. In a pinch, it will withdraw inside its shell.',
    primaryColor: '#084878',
    secondaryColor: '#1068a8',
    accentColor: '#50b0e0',
    borderColor: '#2888c0',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/9.png',
  },
  {
    id: 149,
    name: 'Dragonite',
    type: 'Dragon',
    rarity: 'rare',
    power: 200,
    description: 'A marine Pokémon that flies faster than jets. It is said to be able to circle the globe in just 16 hours.',
    primaryColor: '#b06010',
    secondaryColor: '#d88828',
    accentColor: '#ffc060',
    borderColor: '#c07020',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/149.png',
  },
  {
    id: 134,
    name: 'Vaporeon',
    type: 'Water',
    rarity: 'uncommon',
    power: 130,
    description: 'Its cell composition is similar to water molecules. It can melt into water and become invisible.',
    primaryColor: '#1858a0',
    secondaryColor: '#3080c8',
    accentColor: '#80c8f0',
    borderColor: '#4898d8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/134.png',
  },
  {
    id: 1,
    name: 'Bulbasaur',
    type: 'Grass',
    rarity: 'common',
    power: 60,
    description: 'A strange seed was planted on its back at birth. The plant sprouts and grows with this Pokémon.',
    primaryColor: '#285820',
    secondaryColor: '#508838',
    accentColor: '#90d860',
    borderColor: '#408030',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/1.png',
  },
];

export const RARITY_LABELS = {
  legendary: 'LEGENDARY',
  rare: 'RARE',
  uncommon: 'UNCOMMON',
  common: 'COMMON',
};
