export const PACK_CARDS = [
  {
    id: 1,
    name: 'Inferno Dragon',
    type: 'Monster',
    rarity: 'legendary',
    power: 3200,
    description: 'A fearsome dragon wreathed in eternal flame.',
    primaryColor: '#C0392B',
    secondaryColor: '#E74C3C',
    accentColor: '#F39C12',
    borderColor: '#F1C40F',
  },
  {
    id: 2,
    name: 'Tidal Serpent',
    type: 'Monster',
    rarity: 'rare',
    power: 2400,
    description: 'Born from the deepest ocean trenches.',
    primaryColor: '#1A5276',
    secondaryColor: '#2980B9',
    accentColor: '#AED6F1',
    borderColor: '#5DADE2',
  },
  {
    id: 3,
    name: 'Storm Caller',
    type: 'Spell',
    rarity: 'rare',
    power: null,
    description: 'Summon lightning to strike all enemies.',
    primaryColor: '#7D3C98',
    secondaryColor: '#9B59B6',
    accentColor: '#D7BDE2',
    borderColor: '#A569BD',
  },
  {
    id: 4,
    name: 'Iron Shield',
    type: 'Trap',
    rarity: 'uncommon',
    power: null,
    description: 'Nullify one attack this turn.',
    primaryColor: '#2E4057',
    secondaryColor: '#4A6FA5',
    accentColor: '#A9B7C6',
    borderColor: '#6C8EAD',
  },
  {
    id: 5,
    name: 'Forest Sprite',
    type: 'Monster',
    rarity: 'common',
    power: 800,
    description: 'A gentle spirit of the ancient woods.',
    primaryColor: '#1E8449',
    secondaryColor: '#27AE60',
    accentColor: '#A9DFBF',
    borderColor: '#52BE80',
  },
];

export const RARITY_LABELS = {
  legendary: 'LEGENDARY',
  rare: 'RARE',
  uncommon: 'UNCOMMON',
  common: 'COMMON',
};
