export const PACK_CARDS = [
  {
    id: 6,
    name: 'Charizard',
    type: 'Fire',
    rarity: 'legendary',
    power: 330,
    description: 'Spits fire hot enough to melt boulders. Known to cause forest fires unintentionally.',
    primaryColor: '#b83210',
    secondaryColor: '#e85828',
    accentColor: '#ffd040',
    borderColor: '#ffd040',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/6.png',
  },
  {
    id: 150,
    name: 'Mewtwo',
    type: 'Psychic',
    rarity: 'rare',
    power: 250,
    description: "A Pokémon created by recombining Mew's genes. Said to be the most powerful Pokémon ever.",
    primaryColor: '#6830a0',
    secondaryColor: '#9858c8',
    accentColor: '#e090ff',
    borderColor: '#c078e8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/150.png',
  },
  {
    id: 130,
    name: 'Gyarados',
    type: 'Water',
    rarity: 'rare',
    power: 220,
    description: 'Once it begins to rampage, a Gyarados will burn everything down, even in a harsh storm.',
    primaryColor: '#0c4870',
    secondaryColor: '#1870a8',
    accentColor: '#60c8f0',
    borderColor: '#3898c8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/130.png',
  },
  {
    id: 94,
    name: 'Gengar',
    type: 'Ghost',
    rarity: 'uncommon',
    power: 140,
    description: 'Said to lurk in the shadows of rooms, giggling while watching frightened people.',
    primaryColor: '#3a1860',
    secondaryColor: '#6030a0',
    accentColor: '#c090f0',
    borderColor: '#8050b8',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/94.png',
  },
  {
    id: 25,
    name: 'Pikachu',
    type: 'Electric',
    rarity: 'common',
    power: 70,
    description: 'The electric sacs in its cheeks allow it to unleash powerful thunderbolts without warning.',
    primaryColor: '#a07810',
    secondaryColor: '#d0a820',
    accentColor: '#ffe840',
    borderColor: '#c09018',
    artUrl: 'https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/25.png',
  },
];

export const RARITY_LABELS = {
  legendary: 'LEGENDARY',
  rare: 'RARE',
  uncommon: 'UNCOMMON',
  common: 'COMMON',
};
